language: php

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

matrix:
  include:
    - php: 7.2
      env: LARAVEL='6.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2
      env: LARAVEL='6.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-stable'
    - php: 7.3
      env: LARAVEL='6.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.3
      env: LARAVEL='6.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-stable'
    - php: 7.4snapshot
      env: LARAVEL='6.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4snapshot
      env: LARAVEL='6.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-stable'
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot

before_install:
  - composer config discard-changes true
  - composer validate --no-check-all --strict
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --no-suggest
  - travis_retry composer require --dev satooshi/php-coveralls

script:
  - composer run phpunit -- --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v
